// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slmtnltpycsljtkcmiix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsbXRubHRweWNzbGp0a2NtaWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4ODgwMzcsImV4cCI6MjA2MTQ2NDAzN30.i02AqCYWKe7pJjaqpk5aYrYVrqGpoL2F1LJTnujpTv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);